name: Bitcoin Scraper

on:
  schedule:
  -cron: '*/3 * * * *'
  workflow_dispatch: 
jobs:
 scrape-bitcoin:
 runs-on: ubuntu-latest

 steps:
 -name: Checkout repository
 uses: actions/checkout@v4

 -name: Setup Python
 uses: actions/setup-python@v4
 with: python-version:'3.11'
 -name: Install dependdf
 run: pip install selenium pandas webdriver-manager fake-useragent
 -name: Run scrapper
 run: python scraping.py
 -name: Commit and Push
 run: |
 git config --global user.name "Github Actions"
 git config --global user.email "actions@github.com"
 git add bitcoin_min_data.csv
 git commit -m "Updated Bitcoin data (3-minutes)"
 git push
 